

	CREATE TABLE "TM_LZ"."LT_SRC_DISPLAY_MAPPING" 
   	(	"CATEGORY_CD" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
		"DISPLAY_VALUE" VARCHAR2(100 BYTE), 
		"DISPLAY_LABEL" VARCHAR2(200 BYTE), 
		"DISPLAY_UNIT" VARCHAR2(20 BYTE)
   	)

	create or replace synonym tm_cz.LT_SRC_DISPLAY_MAPPING for "TM_LZ"."LT_SRC_DISPLAY_MAPPING" ;
	grant select, insert, update, delete on  "TM_LZ"."LT_SRC_DISPLAY_MAPPING" to tm_cz;

-------------------------------------------------------------------------------------

 	CREATE TABLE "I2B2DEMODATA"."SAMPLE_DIMENSION" 
  	 (	"SAMPLE_CD" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
		 CONSTRAINT "SAMPLE_DIMENSION_PK" PRIMARY KEY ("SAMPLE_CD")
  	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 	 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT 		CELL_FLASH_CACHE DEFAULT)
 	 TABLESPACE "I2B2_DATA"  ENABLE
  	 )

	
	create or replace synonym tm_cz.SAMPLE_DIMENSION for I2B2DEMODATA.SAMPLE_DIMENSION ;
	grant select, insert, update, delete on  I2B2DEMODATA.SAMPLE_DIMENSION to tm_cz;


-----------------------------------------------------------------------------------------